# Numpy

* Numpy is numerical python

In [1]:
import numpy as np

In [5]:
a1 = np.array([1,2,3,'a1,a2,a3',4+4,2+6,{'name':'ga1day'}])

In [7]:
a1

array([1, 2, 3, 'a1,a2,a3', 8, 8, {'name': 'ga1day'}], dtype=object)

In [8]:
type(a1)

numpy.ndarray

In [9]:
b2 = np . zeros ((9,10),dtype = int)

In [10]:
b2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
b3 = np . arange(7,8,9)

In [12]:
b3

array([7])

In [13]:
b4 = np.ones ((2,3),dtype = int)

In [14]:
b4

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
b5 = np.linspace (15,25,3)

In [18]:
b5

array([15., 20., 25.])

In [19]:
b6 = np .random.randint(2,12,size=(4,6))

In [20]:
b6

array([[ 3,  9, 10, 11,  8,  2],
       [ 5,  4,  7,  2,  2,  8],
       [ 3,  9, 10,  5,  8, 10],
       [ 3, 11,  8, 10,  3,  9]])

In [32]:

b7 = np.full((2,2,2),4)

In [33]:
b7

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [37]:

b8 = np.identity(10)

In [38]:
b8

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [42]:

list = [1,2,3,4,5]
b9= np.asarray(list)

In [43]:
b9

array([1, 2, 3, 4, 5])

In [49]:
b = (9,10)
c = (8,10)

In [50]:

np.multiply (b,c)

array([ 72, 100])

In [51]:
np.divide(b,c)

array([1.125, 1.   ])

In [52]:
divide =np.divide(10,9)

In [53]:
divide

1.1111111111111112

In [54]:
mul = np.multiply(9,10)

In [55]:
mul

90

# aggregation operation

In [58]:
data = np.random.randint(1,10,(2,4))


In [59]:
data

array([[2, 1, 2, 7],
       [9, 9, 9, 3]])

In [60]:
# sum
print(np.sum(data))
print(np.sum(data,axis=0))
print(np.sum(data,axis=1))

42
[11 10 11 10]
[12 30]


In [62]:
data.max()

9

In [63]:
data.min()

1

# numpy array attributes

In [64]:
b1 =np.array([[7,8,9],[3,2,1]])
print (b1.shape)

(2, 3)


In [67]:
b2 = np .array([[7,8,9],[3,2,1]])
print(f"the dimison of b2:",b2.ndim)

the dimison of b2: 2


In [73]:
b2 = np.array ([[7,8,9],[3,2,1]])
print("elemnts in b3 = {b3 sixe}")

elemnts in b3 = {b3 sixe}


In [75]:
b2

array([[7, 8, 9],
       [3, 2, 1]])

In [76]:
b4 = np.array({4,5,6})
print(b4.dtype)

object


# array manipulation

In [80]:

b5 = np.array(np.random.randint(1,6,(6,3)))
b5

array([[2, 3, 2],
       [3, 5, 3],
       [5, 4, 3],
       [1, 5, 1],
       [5, 4, 5],
       [2, 4, 1]])

In [81]:

transpose_array = np.transpose(b5)

In [82]:

transpose_array

array([[2, 3, 5, 1, 5, 2],
       [3, 5, 4, 5, 4, 4],
       [2, 3, 3, 1, 5, 1]])

In [83]:

b6 = np.array(np.random.randint(1,6,(6,3)))

In [84]:
b6

array([[4, 1, 5],
       [1, 5, 3],
       [3, 1, 2],
       [4, 5, 1],
       [3, 3, 3],
       [5, 2, 4]])

In [85]:

b6 = np.array(np.random.randint(1,6,(6,2)))
b6

array([[5, 2],
       [3, 5],
       [5, 4],
       [1, 3],
       [1, 1],
       [1, 4]])

In [86]:
b6.flatten()

array([5, 2, 3, 5, 5, 4, 1, 3, 1, 1, 1, 4])